version: '2.2'

services:
    db:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: todo
            POSTGRES_USER: todo_user
            POSTGRES_PASSWORD: secret